exports.compositoresListPage = function(clist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>][<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EW2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}



// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.compositoresPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Número: </b> ${compositor.id}</li>
                    <li><b>Bio: </b> ${compositor.bio}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            for(let i=1; i < 9; i++){
                key = `tpc${i}`
                if(key in compositor){
                    pagHTML += `
                        <li><b>TPC${i}</b></li>
                    `
                }
            }
    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/"> Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


exports.compositoresFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registar um compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Registar um compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Compositor</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/"> Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}


exports.compositoresFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar os dados de um compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Editar os dados de um compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Compositor</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${a.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${a.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                    </fieldset>
    `;
    
    pagHTML += `
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/"> Voltar</a>]</h5>
                </footer>
            
            </div>
    `;
    return pagHTML;
};

// -------------- Delete Confirmation Page Template ----------------
exports.compositoresFormDeletePage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Eliminar os dados de um compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h2>Tem a certeza que quer eliminar os dados do compositor?</h2>
                </header>
            
    `;
    
    pagHTML += `
                <form action="/compositores/delete/${a.id}" method="POST">
                <br/>
                <button class="w3-btn w3-red w3-mb-2" type="submit">Eliminar</button>
            </form>

            <footer class="w3-container w3-red">
                <h5>Generated by EngWeb2023 in ${d} - [<a href="/"> Voltar</a>]</h5>
            </footer>
            
            </div>
    `;
    return pagHTML;
};

// compositoresPeriodoPage template function
exports.compositoresPeriodoPage = function(compositores, periodo, d) {
    let pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores do Período ${periodo}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Compositores do Período ${periodo}</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Actions</th>
                        </tr>
    `;
    for(let i = 0; i < compositores.length; i++) {
        pagHTML += `
                        <tr>
                            <td>${compositores[i].id}</td>
                            <td>
                                <a href="/compositores/${compositores[i].id}">
                                    ${compositores[i].nome}
                                </a>
                            </td>
                            <td>
                                [<a href="/compositores/edit/${compositores[i].id}">Edit</a>]
                                [<a href="/compositores/delete/${compositores[i].id}">Delete</a>]
                            </td>
                        </tr>
        `;
    }
    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EW2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
    return pagHTML;
}

// periodosListPage template function
exports.periodosListPage = function(periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-khaki">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-black" href="/periodos/criar">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>ID</th><th>Nome</th><th>Actions</th>
                        </tr>
                `
    for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periodos[i].id}</td>
                    <td>
                        <a href="/periodos/${periodos[i].id}">
                            ${periodos[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${periodos[i].id}">Editar</a>][<a href="/periodos/delete/${periodos[i].id}">Apagar Período</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}



exports.periodoEditFromPage = function(periodo, date) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Form</h2>
                </header>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required value="${periodo.id}">
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required value="${periodo.nome}">
                    </fieldset>
                    <br>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Confirm</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${date} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

exports.periodoFormPage = function(date) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-brown">
                    <h2>Periodo Form</h2>
                </header>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required>
                    </fieldset>
                    <br>
                    <button class="w3-btn w3-brown w3-mb-2" type="submit">Register</button>
                </form>
                <footer class="w3-container w3-brown">
                    <h5>Generated by EngWeb2023 in ${date} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

exports.periodoPage = function(periodo, compositores, date) {
    let compositorList = '';
    for (let compositor of compositores) {
        if (compositor.periodo === periodo.id) {
            compositorList += `
            <li>
                <a href="/compositores/">${compositor.nome}</a>
            </li>
            `;
        }
    }
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${periodo.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>${periodo.nome}</h1>
                </header>
                <div class="w3-container">
                    <ul class="w3-ul w3-card-4" style="width:50%">
                        <li>
                            <b>Nome: ${periodo.nome}</b>
                        </li>
                        <li>
                            <b>Id: ${periodo.id}</b>
                        </li>
                        <li>
                            <b>Compositores:</b>
                            <ul>
                                ${compositorList}
                            </ul>
                        </li>
                    </ul>
                </div>
                <footer class="w3-container w3-teal">
                    <address>
                        Generated by EngWeb2024 in ${date} - [<a href="/periodos">Back</a>]
                    </address>
                </footer>
            </div>
        </body>
    </html>
    `;
};





// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}